#!/usr/bin/env python
# Python script to generate HARP2 RGB Images in orthographic projection and plot the orbit using
# multiple L1C files
'''
This script generates RGB images in orthographic projection and save the multiple L1C files in mercator projection.

Usage:
-----

python saveTheOrbitData2nc4.py --l1c_dir </path/to/L1C/dir> --viewIndex 0 --save_dir <path-to-save-nc-file>
'''

# Load the required libraries
from nasa_pace_data_reader import L1
import os
import sys
import argparse
from pathlib import Path
import numpy as np
import netCDF4
import time

try:
    from pyresample import image, geometry, kd_tree
except ImportError as e:
    print('Pyresample package not installed: %s' %e)

# suppress warnings
import warnings
warnings.filterwarnings("ignore")

#--------------------------------------------------------------#
# local functions
#--------------------------------------------------------------#

class Args:
        pass

def create_mercator_netcdf(rgb_matrix, latitude, longitude, viewingAngle, filename="output.nc"):
    """
    Creates a NetCDF4 file from an RGB matrix, latitude, and longitude data.

    Args:
        rgb_matrix (numpy.ndarray): A 3D NumPy array representing the RGB image.
                                   Shape should be (height, width, 3), where 3
                                   represents the Red, Green, and Blue channels.
        latitude (numpy.ndarray): A 2D NumPy array of latitude values.
                                   Shape should be (height, width).
        longitude (numpy.ndarray): A 2D NumPy array of longitude values.
                                    Shape should be (height, width).
        viewingAngle (str): Viewing angle for the RGB image.
        filename (str, optional): The name of the output NetCDF file.
                                   Defaults to "output.nc".

    Raises:
        ValueError: If input arrays have incompatible shapes.
    """

    height, width, channels = rgb_matrix.shape

    if latitude.shape != (height, width) or longitude.shape != (height, width):
        raise ValueError("Latitude and longitude arrays must have the same shape as the RGB matrix (height, width).")
    if channels != 3:
        raise ValueError("RGB Matrix must have 3 channels (Red, Green, Blue)")

    with netCDF4.Dataset(filename, 'w', format='NETCDF4') as ncfile:
        # Dimensions
        ncfile.createDimension('y', height)
        ncfile.createDimension('x', width)
        ncfile.createDimension('bands', 3)  # For R, G, B

        # Variables
        # Latitude
        lat = ncfile.createVariable('lat', 'f4', ('y', 'x'), zlib=True, shuffle=True, complevel=4)
        lat.units = 'degrees_north'
        lat.standard_name = 'latitude'
        lat[:] = latitude

        # Longitude
        lon = ncfile.createVariable('lon', 'f4', ('y', 'x'), zlib=True, shuffle=True, complevel=4)
        lon.units = 'degrees_east'
        lon.standard_name = 'longitude'
        lon[:] = longitude

        # RGB data
        rgb = ncfile.createVariable('rgb', 'f4', ('y', 'x', 'bands'), zlib=True, shuffle=True, complevel=4)
        rgb.units = '1'  # Unitless (just pixel values)
        rgb.long_name = 'Red Green Blue'
        rgb.coordinates = "lon lat" #Crucial: This links the RGB data to the lat/lon variables!

        # if rgb_matrix < 0.00001, use fill value
        rgb_matrix[rgb_matrix < 0.00001] = np.nan

        # Write RGB data, ensuring correct data type
        rgb[:] = rgb_matrix.astype(np.float32)


        # Add global attributes (optional, but good practice)
        ncfile.title = "RGB Image with Latitude/Longitude"
        ncfile.Conventions = "CF-1.8" # Good practice to follow CF conventions
        ncfile.source = "Generated by create_mercator_netcdf function"
        ncfile.viewingAngle = "Viewingle angle, green_angle, blue_angle: %s " %viewingAngle

def resampleData(source_lats, source_lons, target_lats, target_lons,
                 source_data, max_radius, method = 'kd_tree_gauss',
                 *args):
    '''
   

    Parameters
    ----------
    source_lats : TYPE
        Source latitude.
    source_lons : TYPE
        Source longitude.
    target_lats : TYPE
        Target latitude.
    target_lons : TYPE
        Target longitude.
    source_data : TYPE
        Source data for resampling.
    max_radius : TYPE
        The radius around each grid pixel in meters to search for neighbors in the swath..
    *args : TYPE
        DESCRIPTION.
    method : TYPE, optional
        Method for resampling ['nearest_neighbor' or 'kd_tree_guass']. The default is 'nearest_neighbor'.
    *args : TYPE
        DESCRIPTION.

    Returns
    -------
    result : TYPE
        Resampled data.

    '''
    start_time = time.time()
   
    # define the swath of the source instrument
    swath_def = geometry.SwathDefinition(lons = source_lons, lats = source_lats)
   
    # (using nearest neighbour resampling)
    if method == 'nearest_neighbor':
   
        # Define the swath of the target instrument
        swath_def2 = geometry.SwathDefinition(lons = target_lons, lats = target_lats)
       
        # Define the image grid and resample (using nearest neighbour resampling)
        swath_con = image.ImageContainerNearest(source_data, swath_def, radius_of_influence = max_radius)
        area_con = swath_con.resample(swath_def2)
       
        # data in the target grid
        result = area_con.image_data
   
    # Function for resampling using nearest Gussian weighting.
    # The Gauss weigh function is defined as exp(-dist^2/sigma^2).
    # Note the pyresample sigma is not the standard deviation of the gaussian.
    elif method == 'kd_tree_gauss':
   
        # Define a new grid
        grid_def = geometry.GridDefinition(lons=target_lons, lats=target_lats)
       
        # resampling
        result = kd_tree.resample_gauss(swath_def, source_data, grid_def, radius_of_influence=max_radius, sigmas = max_radius/3)
       
    # flaging the unknown data points to nans
    result[result < 1e-5] = np.nan

    # print the time taken for resampling
    print('Time taken for resampling: %s seconds' %(time.time() - start_time))
   
    return result

def update_rgb_with_masked_data(rgb_data_3D, r_, g_, b_):
    """
    Updates an existing RGB matrix with data from masked arrays, replacing
    unmasked values in the original matrix with corresponding values from
    the masked arrays.

    Args:
        rgb_data_3D (numpy.ndarray): The existing 3D RGB array (height, width, 3).
        r_ (numpy.ma.MaskedArray): Masked array for the red channel.
        g_ (numpy.ma.MaskedArray): Masked array for the green channel.
        b_ (numpy.ma.MaskedArray): Masked array for the blue channel.

    Returns:
        numpy.ndarray: The updated rgb_data_3D array.

    Raises:
        ValueError: if input array shapes are not compatible
    """
    height, width, channels = rgb_data_3D.shape
    if channels != 3:
        raise ValueError("rgb_data_3D must have 3 channels (Red, Green, Blue)")
    if not all(arr.shape == (height, width) for arr in [r_, g_, b_]):
        raise ValueError("r_, g_, and b_ must have shape (height, width)")
    if not all(isinstance(arr, np.ma.MaskedArray) for arr in [r_, g_, b_]):
        raise ValueError("r_, g_, and b_ must be numpy.ma.MaskedArray instances")

    # Create a copy to avoid modifying the original in place, if desired
    updated_rgb = rgb_data_3D.copy()

    # Red channel update
    unmasked_indices = ~r_.mask
    updated_rgb[unmasked_indices, 0] = r_.data[unmasked_indices]

    # Green channel update
    unmasked_indices = ~g_.mask
    updated_rgb[unmasked_indices, 1] = g_.data[unmasked_indices]

    # Blue channel update
    unmasked_indices = ~b_.mask
    updated_rgb[unmasked_indices, 2] = b_.data[unmasked_indices]

    return updated_rgb

def plotL1C(args,rgb_data_3D, temp_num=0, viewIndex=[36, 4, 84]):
    """ Plot the L1C file in orthographic projection"""

    # Read the file
    l1c = L1.L1C()
    try:
        l1c_dict = l1c.read(args.l1c_file)

        # save the RGB data
        print('--'*10)
        print('Resampling the data to 8015X6751X3 numpy array...')
        maxRadius = 5200
        if temp_num == 0:
            rgb_data_3D[:, :, 0] = resampleData(l1c_dict['latitude'], l1c_dict['longitude'], lat_2D, lon_2D, l1c_dict['i'][:,:, viewIndex[0],0], maxRadius, method='nearest_neighbor')
            rgb_data_3D[:, :, 1] = resampleData(l1c_dict['latitude'], l1c_dict['longitude'], lat_2D, lon_2D, l1c_dict['i'][:,:, viewIndex[1],0], maxRadius, method='nearest_neighbor')
            rgb_data_3D[:, :, 2] = resampleData(l1c_dict['latitude'], l1c_dict['longitude'], lat_2D, lon_2D, l1c_dict['i'][:,:, viewIndex[2],0], maxRadius, method='nearest_neighbor')
        else:
            r_ = resampleData(l1c_dict['latitude'], l1c_dict['longitude'], lat_2D, lon_2D, l1c_dict['i'][:,:, viewIndex[0],0], maxRadius, method='nearest_neighbor')
            g_ = resampleData(l1c_dict['latitude'], l1c_dict['longitude'], lat_2D, lon_2D, l1c_dict['i'][:,:, viewIndex[1],0], maxRadius, method='nearest_neighbor')
            b_ = resampleData(l1c_dict['latitude'], l1c_dict['longitude'], lat_2D, lon_2D, l1c_dict['i'][:,:, viewIndex[2],0], maxRadius, method='nearest_neighbor')
            # rgb_data_3D[:, :, 0] = np.nansum([rgb_data_3D[:, :, 0], np.ma.getdata(r_)], axis=0)
            # rgb_data_3D[:, :, 1] = np.nansum([rgb_data_3D[:, :, 1], np.ma.getdata(g_)], axis=0)
            # rgb_data_3D[:, :, 2] = np.nansum([rgb_data_3D[:, :, 2], np.ma.getdata(b_)], axis=0)
            rgb_data_3D = update_rgb_with_masked_data(rgb_data_3D, r_, g_, b_)

        return None
        
    except Exception as e:
        print(f'Error: {e}')
        if "NetCDF: HDF error" in str(e):
            print(f'Error: {args.l1c_file} has netCDF error')
            print('---'*10)
            os.system(f'rm -f {args.l1c_file}')
            print(f'Error: {args.l1c_file} has been removed')
            print('---'*10)
        return None

#--------------------------------------------------------------#
# arguments
#--------------------------------------------------------------#

#--------------------------------------------------------------#     
# Parse the command-line arguments
#-- required arguments
parser = argparse.ArgumentParser(description='Generate RGB images/movie from L1C files')
parser.add_argument('--l1c_dir', type=str, required=True, help='L1C dir to process')
parser.add_argument('--save_dir', type=str, required=True, default='', help='Save path for the RGB image')

#-- optional arguments
parser.add_argument('--viewIndex', type=int, required=False, default=0, help='Viewing angle for the RGB image option: 0 = -8, 1 = -43, 2 = ~54, 3 = ~22')
parser.add_argument('--time_range', type=bool, required=False, default=0, help='Time range for the L1C files')


args_ = parser.parse_args()

#--------------------------------------------------------------#
# DEBUG
#--------------------------------------------------------------#
# args_ = Args()
# args_.dpi = 300
# args_.normFactor = 400
# args_.fixed_lat = 1
# args_.fixed_lat = 1
# args_.viewIndex = 0
# args_.movie_only = 0
# args_.viewIndex = 1
# args_.l1c_dir = '/Users/aputhukkudy/Downloads/03-11/hipp381/'
#--------------------------------------------------------------#


# List of L1C files from a directory
l1c_dir = Path(args_.l1c_dir)
l1c_files = sorted(Path(l1c_dir).glob('*5km.nc'))

# sort the L1C files by filename
l1c_files = sorted(l1c_files, key=lambda x: x.name)

#--------------------------------------------------------------#
# select l1c_files in a range (start, end) based on the PACE_HARP2.20240311TXXXX*5km.nc to PACE_HARP2.20240311TYYYY*5km.nc
if bool(args_.time_range):
    start = 'PACE_HARP2.20240311T051500'
    end = 'PACE_HARP2.20240311T065000'

    l1c_files = [x for x in l1c_files if start <= x.name <= end]

#--------------------------------------------------------------#
# angle combination [R, G, B]
#--------------------------------------------------------------

# viewIndex
if args_.viewIndex == 0:
    viewIndex = [36, 4, 84]
elif args_.viewIndex == 1:
    viewIndex = [19, 1, 81]
elif args_.viewIndex == 2:
    viewIndex = [67, 9, 89]
elif args_.viewIndex == 3:
    viewIndex = [49, 6, 86]
elif args_.viewIndex == 4:
    viewIndex = [36, 73, 84]
elif args_.viewIndex == 5:
    viewIndex = [19, 71, 81]
else:
    print('Error: viewIndex must be 0-5')
    sys.exit(1)
#--------------------------------------------------------------#

viewingAngle = ['-8, 4, 84', '-43, 1, 81', '~54, 9, 89', '~22, 6, 86', '-8, 73, 84', '-43, 71, 81']

# Create a temporary number
temp_num = 0

width = 8015
height = 6751

# define a 3D numpy array to store the RGB data
rgb_data_3D = np.zeros((height, width, 3), dtype=np.float32) 

# define a 2D lat and lon array
lat_2D = np.zeros((height, width))
lon_2D = np.zeros((height, width))

# predefine lat and lon arrays, lon is from -180 to 180 and lat is from -90 to 90
lat = np.linspace(-90, 90, height)
lon = np.linspace(-180, 180, width)

# define a 2D lat and lon array using meshgrid
lon_2D, lat_2D = np.meshgrid(lon, lat)

#--------------------------------------------------------------#

# Loop through the L1C files
for l1c_file in l1c_files:
    args_.l1c_file = str(l1c_file)
    args_.save_path = l1c_file.with_suffix('.png')
    print('Projecting RGB for:', args_.l1c_file)
    ax_new = plotL1C(args_, rgb_data_3D, temp_num=temp_num, viewIndex=viewIndex)
    temp_num += 1
#--------------------------------------------------------------#
# Save the RGB_ dict
#--------------------------------------------------------------#

# check if args_.save_path is not empty
if args_.save_dir != '':
    print('--'*10)
    print('Using the save_path to save the nc file: %s' %args_.save_dir)
    save_dir = args_.save_dir
    os.makedirs(save_dir, exist_ok=True)

    # save netCDF
    create_mercator_netcdf(rgb_data_3D, lat_2D, lon_2D,
                           viewingAngle=viewingAngle[args_.viewIndex],
                           filename=f'{save_dir}/RGB_viewIdx_{args_.viewIndex}.nc')
    print(f'RGB data saved in {save_dir}/RGB_viewIdx_{args_.viewIndex}.nc')
        
#-----------------------end of script---------------------------#
